# Generated by Django 5.2.12 on 2026-04-14 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmilePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='smile/photos/%Y/%m/%d/', verbose_name='Фото улыбки')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='smile_photos', to='patient.patient', verbose_name='Пациент')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Фото улыбки',
                'verbose_name_plural': 'Фото улыбок',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SmileAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обработка'), ('done', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('landmarks', models.JSONField(blank=True, default=dict, help_text='Все 478 точек MediaPipe Face Mesh: {idx: {x, y, z}}', verbose_name='Landmarks лица')),
                ('teeth_contour', models.JSONField(blank=True, default=list, help_text='Видимая зона зубов (нижний край верхней губы + верхний край нижней губы): [{x, y}, ...]', verbose_name='Контур зубов')),
                ('lip_contour', models.JSONField(blank=True, default=list, help_text='Внешний контур губ (справочный): [{x, y}, ...]', verbose_name='Контур губ')),
                ('contour_image', models.ImageField(blank=True, upload_to='smile/contours/%Y/%m/%d/', verbose_name='Фото с контуром')),
                ('guidelines', models.JSONField(blank=True, default=dict, help_text='{"facial_midline": {...}, "smile_arc": [...], ...}', verbose_name='Направляющие')),
                ('guidelines_image', models.ImageField(blank=True, upload_to='smile/guidelines/%Y/%m/%d/', verbose_name='Фото с направляющими')),
                ('cutout_image', models.ImageField(blank=True, upload_to='smile/cutouts/%Y/%m/%d/', verbose_name='Вырезка улыбки (прозрачный фон)')),
                ('masked_image', models.ImageField(blank=True, upload_to='smile/masked/%Y/%m/%d/', verbose_name='Фото с прозрачной зоной улыбки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='smile.smilephoto', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Анализ улыбки',
                'verbose_name_plural': 'Анализы улыбок',
                'ordering': ['-updated_at'],
            },
        ),
    ]
