# Generated by Django 5.2.12 on 2026-03-09 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание исследования')),
                ('file', models.FileField(upload_to='dicom/%Y/%m/%d/', verbose_name='DICOM файл (.dcm / .zip)')),
                ('orthanc_study_id', models.CharField(blank=True, editable=False, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_studies', to='patient.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'DICOM исследование',
                'verbose_name_plural': 'DICOM исследования',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
