# Generated by Django 5.2.12 on 2026-03-09 08:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DicomStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255, verbose_name='Имя пациента')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание исследования')),
                ('file', models.FileField(upload_to='dicom/%Y/%m/%d/', verbose_name='DICOM файл (.dcm / .zip)')),
                ('orthanc_study_id', models.CharField(blank=True, editable=False, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DICOM исследование',
                'verbose_name_plural': 'DICOM исследования',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
