# Generated by Django 5.2.12 on 2026-03-09 16:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0001_initial'),
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomstudy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dicom_studies', to='patient.patient', verbose_name='Пациент'),
        ),
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('total_size', models.BigIntegerField(verbose_name='Размер файла (байт)')),
                ('offset', models.BigIntegerField(default=0, verbose_name='Загружено (байт)')),
                ('status', models.CharField(choices=[('uploading', 'Загружается'), ('complete', 'Завершён'), ('failed', 'Ошибка')], default='uploading', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Загрузка чанками',
                'verbose_name_plural': 'Загрузки чанками',
            },
        ),
    ]
