# Generated by Django 5.2.12 on 2026-03-09 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='service.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Цена услуги',
                'verbose_name_plural': 'Прайс-лист',
                'ordering': ['service__stage__order', 'service__order'],
            },
        ),
    ]
