# Generated by Django 5.2.12 on 2026-03-09 13:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Этап (справочник)',
                'verbose_name_plural': 'Этапы (справочник)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата завершения')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='staff.staff', verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='patient.patient', verbose_name='Пациент')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='treatment.stage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Лечение',
                'verbose_name_plural': 'Лечения',
                'ordering': ['-started_at'],
            },
        ),
    ]
