# Generated by Django 5.2.12 on 2026-03-09 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='patient.patient', verbose_name='Пациент'),
        ),
    ]
