# Generated by Django 5.2.12 on 2026-03-09 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='treatment.stage', verbose_name='Этап'),
        ),
    ]
