# Generated by Django 5.2.12 on 2026-03-25 10:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StlScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('archive', models.FileField(upload_to='stl/%Y/%m/%d/', verbose_name='ZIP архив')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stl_scans', to='patient.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'STL снимок',
                'verbose_name_plural': 'STL снимки',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StlFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to='stl/files/%Y/%m/%d/', verbose_name='STL файл')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='stl.stlscan', verbose_name='Снимок')),
            ],
            options={
                'verbose_name': 'STL файл',
                'verbose_name_plural': 'STL файлы',
                'ordering': ['name'],
            },
        ),
    ]
