# Generated by Django 5.2.12 on 2026-03-25 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stl', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stlfile',
            name='category',
            field=models.CharField(choices=[('upper', 'Верхняя челюсть'), ('lower', 'Нижняя челюсть'), ('buccal', 'Буккальный'), ('other', 'Другое')], default='other', max_length=10, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='StlAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('text', models.TextField(verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='stl.stlscan', verbose_name='Снимок')),
            ],
            options={
                'verbose_name': 'Аннотация',
                'verbose_name_plural': 'Аннотации',
                'ordering': ['created_at'],
            },
        ),
    ]
