# Generated by Django 5.2.12 on 2026-03-25 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stl', '0002_stlfile_category_stlannotation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StlSegmentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('manual', 'Ручная'), ('auto', 'Автоматическая'), ('corrected', 'Скорректированная')], default='manual', max_length=10, verbose_name='Источник')),
                ('labels', models.JSONField(default=dict, help_text='{"tooth_11": [0, 1, 2, ...], "gingiva": [55, 56, ...]}', verbose_name='Метки сегментации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('stl_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentations', to='stl.stlfile', verbose_name='STL файл')),
            ],
            options={
                'verbose_name': 'Сегментация',
                'verbose_name_plural': 'Сегментации',
                'ordering': ['-updated_at'],
            },
        ),
    ]
